// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommitmentRequest - 服务器提交属性承诺与分片
type CommitmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`                  // 服务器 ID
	Commitment     []byte                 `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`                               // Pedersen 承诺 C = m*G + r*H (序列化)
	RerandomShards [][]byte               `protobuf:"bytes,3,rep,name=rerandom_shards,json=rerandomShards,proto3" json:"rerandom_shards,omitempty"` // 重随机化分片 r'_i (每个分片对应一个 MPC 节点)
	GeneratorG     []byte                 `protobuf:"bytes,4,opt,name=generator_g,json=generatorG,proto3" json:"generator_g,omitempty"`             // 生成元 G (发送给客户端)
	AttributeId    int32                  `protobuf:"varint,5,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`         // 属性 ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitmentRequest) Reset() {
	*x = CommitmentRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentRequest) ProtoMessage() {}

func (x *CommitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentRequest.ProtoReflect.Descriptor instead.
func (*CommitmentRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CommitmentRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *CommitmentRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *CommitmentRequest) GetRerandomShards() [][]byte {
	if x != nil {
		return x.RerandomShards
	}
	return nil
}

func (x *CommitmentRequest) GetGeneratorG() []byte {
	if x != nil {
		return x.GeneratorG
	}
	return nil
}

func (x *CommitmentRequest) GetAttributeId() int32 {
	if x != nil {
		return x.AttributeId
	}
	return 0
}

// CommitmentResponse - 服务器提交响应
type CommitmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitmentResponse) Reset() {
	*x = CommitmentResponse{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentResponse) ProtoMessage() {}

func (x *CommitmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentResponse.ProtoReflect.Descriptor instead.
func (*CommitmentResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CommitmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ClientParamsRequest - 客户端参数分片
type ClientParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientShards  [][]byte               `protobuf:"bytes,1,rep,name=client_shards,json=clientShards,proto3" json:"client_shards,omitempty"` // 客户端参数分片 (每个分片对应一个 MPC 节点)
	ClientId      int32                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientParamsRequest) Reset() {
	*x = ClientParamsRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientParamsRequest) ProtoMessage() {}

func (x *ClientParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientParamsRequest.ProtoReflect.Descriptor instead.
func (*ClientParamsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ClientParamsRequest) GetClientShards() [][]byte {
	if x != nil {
		return x.ClientShards
	}
	return nil
}

func (x *ClientParamsRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

// ClientParamsResponse - 客户端提交响应
type ClientParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientParamsResponse) Reset() {
	*x = ClientParamsResponse{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientParamsResponse) ProtoMessage() {}

func (x *ClientParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientParamsResponse.ProtoReflect.Descriptor instead.
func (*ClientParamsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ClientParamsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientParamsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PermutationRequest - 用户提交置换顺序
type PermutationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permutation   []int32                `protobuf:"varint,1,rep,packed,name=permutation,proto3" json:"permutation,omitempty"` // 置换数组 π
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermutationRequest) Reset() {
	*x = PermutationRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermutationRequest) ProtoMessage() {}

func (x *PermutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermutationRequest.ProtoReflect.Descriptor instead.
func (*PermutationRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *PermutationRequest) GetPermutation() []int32 {
	if x != nil {
		return x.Permutation
	}
	return nil
}

func (x *PermutationRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// PermutationResponse - 置换响应 (包含置换后的承诺)
type PermutationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PermutedCommitments [][]byte               `protobuf:"bytes,1,rep,name=permuted_commitments,json=permutedCommitments,proto3" json:"permuted_commitments,omitempty"` // 置换后的重随机化承诺
	Success             bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PermutationResponse) Reset() {
	*x = PermutationResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermutationResponse) ProtoMessage() {}

func (x *PermutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermutationResponse.ProtoReflect.Descriptor instead.
func (*PermutationResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *PermutationResponse) GetPermutedCommitments() [][]byte {
	if x != nil {
		return x.PermutedCommitments
	}
	return nil
}

func (x *PermutationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PermutationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MerkleRootRequest - 请求 Merkle Root
type MerkleRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootRequest) Reset() {
	*x = MerkleRootRequest{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootRequest) ProtoMessage() {}

func (x *MerkleRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootRequest.ProtoReflect.Descriptor instead.
func (*MerkleRootRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

// MerkleRootResponse - Merkle Root 响应
type MerkleRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleRoot    []byte                 `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	NumLeaves     int32                  `protobuf:"varint,2,opt,name=num_leaves,json=numLeaves,proto3" json:"num_leaves,omitempty"`
	LeafHashes    [][]byte               `protobuf:"bytes,3,rep,name=leaf_hashes,json=leafHashes,proto3" json:"leaf_hashes,omitempty"` // 叶子哈希 (用于 proof 生成)
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootResponse) Reset() {
	*x = MerkleRootResponse{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootResponse) ProtoMessage() {}

func (x *MerkleRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootResponse.ProtoReflect.Descriptor instead.
func (*MerkleRootResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *MerkleRootResponse) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *MerkleRootResponse) GetNumLeaves() int32 {
	if x != nil {
		return x.NumLeaves
	}
	return 0
}

func (x *MerkleRootResponse) GetLeafHashes() [][]byte {
	if x != nil {
		return x.LeafHashes
	}
	return nil
}

func (x *MerkleRootResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress   string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	PeerSequence  int32                  `protobuf:"varint,2,opt,name=peer_sequence,json=peerSequence,proto3" json:"peer_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *MatchResponse) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *MatchResponse) GetPeerSequence() int32 {
	if x != nil {
		return x.PeerSequence
	}
	return 0
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,2,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ResultRequest) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ResultRequest) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessedData []byte                 `protobuf:"bytes,1,opt,name=processed_data,json=processedData,proto3" json:"processed_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ResultResponse) GetProcessedData() []byte {
	if x != nil {
		return x.ProcessedData
	}
	return nil
}

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedMessage []byte                 `protobuf:"bytes,1,opt,name=signed_message,json=signedMessage,proto3" json:"signed_message,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *SignRequest) GetSignedMessage() []byte {
	if x != nil {
		return x.SignedMessage
	}
	return nil
}

func (x *SignRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggrResult    []byte                 `protobuf:"bytes,1,opt,name=aggr_result,json=aggrResult,proto3" json:"aggr_result,omitempty"`
	MerkleRoot    []byte                 `protobuf:"bytes,2,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *SignResponse) GetAggrResult() []byte {
	if x != nil {
		return x.AggrResult
	}
	return nil
}

func (x *SignResponse) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ClientData    []byte                 `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *Message) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Message) GetClientData() []byte {
	if x != nil {
		return x.ClientData
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x05proto\"\xbd\x01\n" +
	"\x11CommitmentRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1e\n" +
	"\n" +
	"commitment\x18\x02 \x01(\fR\n" +
	"commitment\x12'\n" +
	"\x0frerandom_shards\x18\x03 \x03(\fR\x0ererandomShards\x12\x1f\n" +
	"\vgenerator_g\x18\x04 \x01(\fR\n" +
	"generatorG\x12!\n" +
	"\fattribute_id\x18\x05 \x01(\x05R\vattributeId\"H\n" +
	"\x12CommitmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x13ClientParamsRequest\x12#\n" +
	"\rclient_shards\x18\x01 \x03(\fR\fclientShards\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x05R\bclientId\"J\n" +
	"\x14ClientParamsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x12PermutationRequest\x12 \n" +
	"\vpermutation\x18\x01 \x03(\x05R\vpermutation\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"|\n" +
	"\x13PermutationResponse\x121\n" +
	"\x14permuted_commitments\x18\x01 \x03(\fR\x13permutedCommitments\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x13\n" +
	"\x11MerkleRootRequest\"\x8f\x01\n" +
	"\x12MerkleRootResponse\x12\x1f\n" +
	"\vmerkle_root\x18\x01 \x01(\fR\n" +
	"merkleRoot\x12\x1d\n" +
	"\n" +
	"num_leaves\x18\x02 \x01(\x05R\tnumLeaves\x12\x1f\n" +
	"\vleaf_hashes\x18\x03 \x03(\fR\n" +
	"leafHashes\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"+\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"W\n" +
	"\rMatchResponse\x12!\n" +
	"\fpeer_address\x18\x01 \x01(\tR\vpeerAddress\x12#\n" +
	"\rpeer_sequence\x18\x02 \x01(\x05R\fpeerSequence\"L\n" +
	"\rResultRequest\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x1f\n" +
	"\vresult_data\x18\x02 \x01(\fR\n" +
	"resultData\"7\n" +
	"\x0eResultResponse\x12%\n" +
	"\x0eprocessed_data\x18\x01 \x01(\fR\rprocessedData\"S\n" +
	"\vSignRequest\x12%\n" +
	"\x0esigned_message\x18\x01 \x01(\fR\rsignedMessage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"P\n" +
	"\fSignResponse\x12\x1f\n" +
	"\vaggr_result\x18\x01 \x01(\fR\n" +
	"aggrResult\x12\x1f\n" +
	"\vmerkle_root\x18\x02 \x01(\fR\n" +
	"merkleRoot\"F\n" +
	"\aMessage\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x1f\n" +
	"\vclient_data\x18\x02 \x01(\fR\n" +
	"clientData2\xb6\x02\n" +
	"\n" +
	"DIDService\x12G\n" +
	"\x10SubmitCommitment\x12\x18.proto.CommitmentRequest\x1a\x19.proto.CommitmentResponse\x12M\n" +
	"\x12SubmitClientParams\x12\x1a.proto.ClientParamsRequest\x1a\x1b.proto.ClientParamsResponse\x12J\n" +
	"\x11SubmitPermutation\x12\x19.proto.PermutationRequest\x1a\x1a.proto.PermutationResponse\x12D\n" +
	"\rGetMerkleRoot\x12\x18.proto.MerkleRootRequest\x1a\x19.proto.MerkleRootResponse2\xbd\x01\n" +
	"\fMatchService\x128\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\x14.proto.MatchResponse\x12;\n" +
	"\fSubmitResult\x12\x14.proto.ResultRequest\x1a\x15.proto.ResultResponse\x126\n" +
	"\vSignMessage\x12\x12.proto.SignRequest\x1a\x13.proto.SignResponse29\n" +
	"\vChatService\x12*\n" +
	"\x04Chat\x12\x0e.proto.Message\x1a\x0e.proto.Message(\x010\x01B\vZ\tDID/protob\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_chat_proto_goTypes = []any{
	(*CommitmentRequest)(nil),    // 0: proto.CommitmentRequest
	(*CommitmentResponse)(nil),   // 1: proto.CommitmentResponse
	(*ClientParamsRequest)(nil),  // 2: proto.ClientParamsRequest
	(*ClientParamsResponse)(nil), // 3: proto.ClientParamsResponse
	(*PermutationRequest)(nil),   // 4: proto.PermutationRequest
	(*PermutationResponse)(nil),  // 5: proto.PermutationResponse
	(*MerkleRootRequest)(nil),    // 6: proto.MerkleRootRequest
	(*MerkleRootResponse)(nil),   // 7: proto.MerkleRootResponse
	(*RegisterRequest)(nil),      // 8: proto.RegisterRequest
	(*MatchResponse)(nil),        // 9: proto.MatchResponse
	(*ResultRequest)(nil),        // 10: proto.ResultRequest
	(*ResultResponse)(nil),       // 11: proto.ResultResponse
	(*SignRequest)(nil),          // 12: proto.SignRequest
	(*SignResponse)(nil),         // 13: proto.SignResponse
	(*Message)(nil),              // 14: proto.Message
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: proto.DIDService.SubmitCommitment:input_type -> proto.CommitmentRequest
	2,  // 1: proto.DIDService.SubmitClientParams:input_type -> proto.ClientParamsRequest
	4,  // 2: proto.DIDService.SubmitPermutation:input_type -> proto.PermutationRequest
	6,  // 3: proto.DIDService.GetMerkleRoot:input_type -> proto.MerkleRootRequest
	8,  // 4: proto.MatchService.Register:input_type -> proto.RegisterRequest
	10, // 5: proto.MatchService.SubmitResult:input_type -> proto.ResultRequest
	12, // 6: proto.MatchService.SignMessage:input_type -> proto.SignRequest
	14, // 7: proto.ChatService.Chat:input_type -> proto.Message
	1,  // 8: proto.DIDService.SubmitCommitment:output_type -> proto.CommitmentResponse
	3,  // 9: proto.DIDService.SubmitClientParams:output_type -> proto.ClientParamsResponse
	5,  // 10: proto.DIDService.SubmitPermutation:output_type -> proto.PermutationResponse
	7,  // 11: proto.DIDService.GetMerkleRoot:output_type -> proto.MerkleRootResponse
	9,  // 12: proto.MatchService.Register:output_type -> proto.MatchResponse
	11, // 13: proto.MatchService.SubmitResult:output_type -> proto.ResultResponse
	13, // 14: proto.MatchService.SignMessage:output_type -> proto.SignResponse
	14, // 15: proto.ChatService.Chat:output_type -> proto.Message
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
