// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: chat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DIDService_SubmitCommitments_FullMethodName  = "/proto.DIDService/SubmitCommitments"
	DIDService_SubmitClientParams_FullMethodName = "/proto.DIDService/SubmitClientParams"
	DIDService_SubmitPermutation_FullMethodName  = "/proto.DIDService/SubmitPermutation"
	DIDService_GetMerkleRoot_FullMethodName      = "/proto.DIDService/GetMerkleRoot"
	DIDService_SubscribeGenerator_FullMethodName = "/proto.DIDService/SubscribeGenerator"
	DIDService_WaitForStage_FullMethodName       = "/proto.DIDService/WaitForStage"
)

// DIDServiceClient is the client API for DIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DIDService 是新架构的核心协调服务
// 服务器生成属性与 Pedersen 承诺, 计算分片发送到 MPC 节点
// 客户端基于 g 计算新参数, 分片发送到 MPC 节点
// MPC 节点执行重随机化与不经意置换
type DIDServiceClient interface {
	// 服务器端: 流式批量提交属性承诺与 MPC 分片 (减少 N 次 TLS 握手开销)
	SubmitCommitments(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CommitmentRequest, CommitmentResponse], error)
	// 客户端: 接收生成元 g, 提交客户端参数分片
	SubmitClientParams(ctx context.Context, in *ClientParamsRequest, opts ...grpc.CallOption) (*ClientParamsResponse, error)
	// 用户: 提交属性置换顺序 (用于 ORP)
	SubmitPermutation(ctx context.Context, in *PermutationRequest, opts ...grpc.CallOption) (*PermutationResponse, error)
	// 获取最终 Merkle Root
	GetMerkleRoot(ctx context.Context, in *MerkleRootRequest, opts ...grpc.CallOption) (*MerkleRootResponse, error)
	// 客户端订阅生成元 G (服务器推送 G 到客户端, 替代本地伪造)
	SubscribeGenerator(ctx context.Context, in *GeneratorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GeneratorResponse], error)
	// 等待阶段完成 (阻塞等待直到指定阶段就绪, 替代 poll-and-fail)
	WaitForStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*StageResponse, error)
}

type dIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDIDServiceClient(cc grpc.ClientConnInterface) DIDServiceClient {
	return &dIDServiceClient{cc}
}

func (c *dIDServiceClient) SubmitCommitments(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CommitmentRequest, CommitmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DIDService_ServiceDesc.Streams[0], DIDService_SubmitCommitments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommitmentRequest, CommitmentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DIDService_SubmitCommitmentsClient = grpc.ClientStreamingClient[CommitmentRequest, CommitmentResponse]

func (c *dIDServiceClient) SubmitClientParams(ctx context.Context, in *ClientParamsRequest, opts ...grpc.CallOption) (*ClientParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientParamsResponse)
	err := c.cc.Invoke(ctx, DIDService_SubmitClientParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) SubmitPermutation(ctx context.Context, in *PermutationRequest, opts ...grpc.CallOption) (*PermutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermutationResponse)
	err := c.cc.Invoke(ctx, DIDService_SubmitPermutation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) GetMerkleRoot(ctx context.Context, in *MerkleRootRequest, opts ...grpc.CallOption) (*MerkleRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleRootResponse)
	err := c.cc.Invoke(ctx, DIDService_GetMerkleRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) SubscribeGenerator(ctx context.Context, in *GeneratorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GeneratorResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DIDService_ServiceDesc.Streams[1], DIDService_SubscribeGenerator_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GeneratorRequest, GeneratorResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DIDService_SubscribeGeneratorClient = grpc.ServerStreamingClient[GeneratorResponse]

func (c *dIDServiceClient) WaitForStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*StageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageResponse)
	err := c.cc.Invoke(ctx, DIDService_WaitForStage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DIDServiceServer is the server API for DIDService service.
// All implementations must embed UnimplementedDIDServiceServer
// for forward compatibility.
//
// DIDService 是新架构的核心协调服务
// 服务器生成属性与 Pedersen 承诺, 计算分片发送到 MPC 节点
// 客户端基于 g 计算新参数, 分片发送到 MPC 节点
// MPC 节点执行重随机化与不经意置换
type DIDServiceServer interface {
	// 服务器端: 流式批量提交属性承诺与 MPC 分片 (减少 N 次 TLS 握手开销)
	SubmitCommitments(grpc.ClientStreamingServer[CommitmentRequest, CommitmentResponse]) error
	// 客户端: 接收生成元 g, 提交客户端参数分片
	SubmitClientParams(context.Context, *ClientParamsRequest) (*ClientParamsResponse, error)
	// 用户: 提交属性置换顺序 (用于 ORP)
	SubmitPermutation(context.Context, *PermutationRequest) (*PermutationResponse, error)
	// 获取最终 Merkle Root
	GetMerkleRoot(context.Context, *MerkleRootRequest) (*MerkleRootResponse, error)
	// 客户端订阅生成元 G (服务器推送 G 到客户端, 替代本地伪造)
	SubscribeGenerator(*GeneratorRequest, grpc.ServerStreamingServer[GeneratorResponse]) error
	// 等待阶段完成 (阻塞等待直到指定阶段就绪, 替代 poll-and-fail)
	WaitForStage(context.Context, *StageRequest) (*StageResponse, error)
	mustEmbedUnimplementedDIDServiceServer()
}

// UnimplementedDIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDIDServiceServer struct{}

func (UnimplementedDIDServiceServer) SubmitCommitments(grpc.ClientStreamingServer[CommitmentRequest, CommitmentResponse]) error {
	return status.Error(codes.Unimplemented, "method SubmitCommitments not implemented")
}
func (UnimplementedDIDServiceServer) SubmitClientParams(context.Context, *ClientParamsRequest) (*ClientParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitClientParams not implemented")
}
func (UnimplementedDIDServiceServer) SubmitPermutation(context.Context, *PermutationRequest) (*PermutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPermutation not implemented")
}
func (UnimplementedDIDServiceServer) GetMerkleRoot(context.Context, *MerkleRootRequest) (*MerkleRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerkleRoot not implemented")
}
func (UnimplementedDIDServiceServer) SubscribeGenerator(*GeneratorRequest, grpc.ServerStreamingServer[GeneratorResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeGenerator not implemented")
}
func (UnimplementedDIDServiceServer) WaitForStage(context.Context, *StageRequest) (*StageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForStage not implemented")
}
func (UnimplementedDIDServiceServer) mustEmbedUnimplementedDIDServiceServer() {}
func (UnimplementedDIDServiceServer) testEmbeddedByValue()                    {}

// UnsafeDIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DIDServiceServer will
// result in compilation errors.
type UnsafeDIDServiceServer interface {
	mustEmbedUnimplementedDIDServiceServer()
}

func RegisterDIDServiceServer(s grpc.ServiceRegistrar, srv DIDServiceServer) {
	// If the following call panics, it indicates UnimplementedDIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DIDService_ServiceDesc, srv)
}

func _DIDService_SubmitCommitments_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DIDServiceServer).SubmitCommitments(&grpc.GenericServerStream[CommitmentRequest, CommitmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DIDService_SubmitCommitmentsServer = grpc.ClientStreamingServer[CommitmentRequest, CommitmentResponse]

func _DIDService_SubmitClientParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).SubmitClientParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_SubmitClientParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).SubmitClientParams(ctx, req.(*ClientParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_SubmitPermutation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).SubmitPermutation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_SubmitPermutation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).SubmitPermutation(ctx, req.(*PermutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_GetMerkleRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerkleRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).GetMerkleRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_GetMerkleRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).GetMerkleRoot(ctx, req.(*MerkleRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_SubscribeGenerator_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GeneratorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DIDServiceServer).SubscribeGenerator(m, &grpc.GenericServerStream[GeneratorRequest, GeneratorResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DIDService_SubscribeGeneratorServer = grpc.ServerStreamingServer[GeneratorResponse]

func _DIDService_WaitForStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).WaitForStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_WaitForStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).WaitForStage(ctx, req.(*StageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DIDService_ServiceDesc is the grpc.ServiceDesc for DIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DIDService",
	HandlerType: (*DIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitClientParams",
			Handler:    _DIDService_SubmitClientParams_Handler,
		},
		{
			MethodName: "SubmitPermutation",
			Handler:    _DIDService_SubmitPermutation_Handler,
		},
		{
			MethodName: "GetMerkleRoot",
			Handler:    _DIDService_GetMerkleRoot_Handler,
		},
		{
			MethodName: "WaitForStage",
			Handler:    _DIDService_WaitForStage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitCommitments",
			Handler:       _DIDService_SubmitCommitments_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeGenerator",
			Handler:       _DIDService_SubscribeGenerator_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}

const (
	MPCNodeService_ReceiveShards_FullMethodName       = "/proto.MPCNodeService/ReceiveShards"
	MPCNodeService_ReceiveClientShard_FullMethodName  = "/proto.MPCNodeService/ReceiveClientShard"
	MPCNodeService_ComputeContribution_FullMethodName = "/proto.MPCNodeService/ComputeContribution"
	MPCNodeService_PermuteShards_FullMethodName       = "/proto.MPCNodeService/PermuteShards"
	MPCNodeService_HealthCheck_FullMethodName         = "/proto.MPCNodeService/HealthCheck"
)

// MPCNodeServiceClient is the client API for MPCNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MPCNodeService - MPC 节点服务 (基于消息队列模式)
// 每个 MPC 节点作为独立 gRPC 服务, 接收分片并计算贡献
// 协调节点通过此服务与各 MPC 节点通信, 实现真正的分布式 MPC
type MPCNodeServiceClient interface {
	// 接收服务器分片 (流式, 支持批量)
	ReceiveShards(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShardMessage, MPCResponse], error)
	// 接收客户端分片
	ReceiveClientShard(ctx context.Context, in *ClientShardMessage, opts ...grpc.CallOption) (*MPCResponse, error)
	// 请求节点计算重随机化贡献
	ComputeContribution(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ContributionResponse, error)
	// 置换分片 (ORP 协作)
	PermuteShards(ctx context.Context, in *PermuteRequest, opts ...grpc.CallOption) (*MPCResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mPCNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCNodeServiceClient(cc grpc.ClientConnInterface) MPCNodeServiceClient {
	return &mPCNodeServiceClient{cc}
}

func (c *mPCNodeServiceClient) ReceiveShards(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShardMessage, MPCResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MPCNodeService_ServiceDesc.Streams[0], MPCNodeService_ReceiveShards_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShardMessage, MPCResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCNodeService_ReceiveShardsClient = grpc.ClientStreamingClient[ShardMessage, MPCResponse]

func (c *mPCNodeServiceClient) ReceiveClientShard(ctx context.Context, in *ClientShardMessage, opts ...grpc.CallOption) (*MPCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MPCResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_ReceiveClientShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) ComputeContribution(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContributionResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_ComputeContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) PermuteShards(ctx context.Context, in *PermuteRequest, opts ...grpc.CallOption) (*MPCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MPCResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_PermuteShards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCNodeServiceServer is the server API for MPCNodeService service.
// All implementations must embed UnimplementedMPCNodeServiceServer
// for forward compatibility.
//
// MPCNodeService - MPC 节点服务 (基于消息队列模式)
// 每个 MPC 节点作为独立 gRPC 服务, 接收分片并计算贡献
// 协调节点通过此服务与各 MPC 节点通信, 实现真正的分布式 MPC
type MPCNodeServiceServer interface {
	// 接收服务器分片 (流式, 支持批量)
	ReceiveShards(grpc.ClientStreamingServer[ShardMessage, MPCResponse]) error
	// 接收客户端分片
	ReceiveClientShard(context.Context, *ClientShardMessage) (*MPCResponse, error)
	// 请求节点计算重随机化贡献
	ComputeContribution(context.Context, *ComputeRequest) (*ContributionResponse, error)
	// 置换分片 (ORP 协作)
	PermuteShards(context.Context, *PermuteRequest) (*MPCResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMPCNodeServiceServer()
}

// UnimplementedMPCNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCNodeServiceServer struct{}

func (UnimplementedMPCNodeServiceServer) ReceiveShards(grpc.ClientStreamingServer[ShardMessage, MPCResponse]) error {
	return status.Error(codes.Unimplemented, "method ReceiveShards not implemented")
}
func (UnimplementedMPCNodeServiceServer) ReceiveClientShard(context.Context, *ClientShardMessage) (*MPCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveClientShard not implemented")
}
func (UnimplementedMPCNodeServiceServer) ComputeContribution(context.Context, *ComputeRequest) (*ContributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeContribution not implemented")
}
func (UnimplementedMPCNodeServiceServer) PermuteShards(context.Context, *PermuteRequest) (*MPCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PermuteShards not implemented")
}
func (UnimplementedMPCNodeServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMPCNodeServiceServer) mustEmbedUnimplementedMPCNodeServiceServer() {}
func (UnimplementedMPCNodeServiceServer) testEmbeddedByValue()                        {}

// UnsafeMPCNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCNodeServiceServer will
// result in compilation errors.
type UnsafeMPCNodeServiceServer interface {
	mustEmbedUnimplementedMPCNodeServiceServer()
}

func RegisterMPCNodeServiceServer(s grpc.ServiceRegistrar, srv MPCNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedMPCNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCNodeService_ServiceDesc, srv)
}

func _MPCNodeService_ReceiveShards_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MPCNodeServiceServer).ReceiveShards(&grpc.GenericServerStream[ShardMessage, MPCResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCNodeService_ReceiveShardsServer = grpc.ClientStreamingServer[ShardMessage, MPCResponse]

func _MPCNodeService_ReceiveClientShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientShardMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).ReceiveClientShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_ReceiveClientShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).ReceiveClientShard(ctx, req.(*ClientShardMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_ComputeContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).ComputeContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_ComputeContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).ComputeContribution(ctx, req.(*ComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_PermuteShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).PermuteShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_PermuteShards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).PermuteShards(ctx, req.(*PermuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCNodeService_ServiceDesc is the grpc.ServiceDesc for MPCNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MPCNodeService",
	HandlerType: (*MPCNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveClientShard",
			Handler:    _MPCNodeService_ReceiveClientShard_Handler,
		},
		{
			MethodName: "ComputeContribution",
			Handler:    _MPCNodeService_ComputeContribution_Handler,
		},
		{
			MethodName: "PermuteShards",
			Handler:    _MPCNodeService_PermuteShards_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MPCNodeService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveShards",
			Handler:       _MPCNodeService_ReceiveShards_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}

const (
	MatchService_Register_FullMethodName     = "/proto.MatchService/Register"
	MatchService_SubmitResult_FullMethodName = "/proto.MatchService/SubmitResult"
	MatchService_SignMessage_FullMethodName  = "/proto.MatchService/SignMessage"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	SubmitResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	SignMessage(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, MatchService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) SubmitResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, MatchService_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) SignMessage(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, MatchService_SignMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility.
type MatchServiceServer interface {
	Register(context.Context, *RegisterRequest) (*MatchResponse, error)
	SubmitResult(context.Context, *ResultRequest) (*ResultResponse, error)
	SignMessage(context.Context, *SignRequest) (*SignResponse, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchServiceServer struct{}

func (UnimplementedMatchServiceServer) Register(context.Context, *RegisterRequest) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedMatchServiceServer) SubmitResult(context.Context, *ResultRequest) (*ResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedMatchServiceServer) SignMessage(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignMessage not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}
func (UnimplementedMatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).SubmitResult(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_SignMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).SignMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_SignMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).SignMessage(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _MatchService_Register_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _MatchService_SubmitResult_Handler,
		},
		{
			MethodName: "SignMessage",
			Handler:    _MatchService_SignMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}

const (
	ChatService_Chat_FullMethodName = "/proto.ChatService/Chat"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 点对点：ChatService
type ChatServiceClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatClient = grpc.BidiStreamingClient[Message, Message]

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// 点对点：ChatService
type ChatServiceServer interface {
	Chat(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) Chat(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).Chat(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatServer = grpc.BidiStreamingServer[Message, Message]

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ChatService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
